//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction
    {
        public int Id { get; set; }
        public Nullable<int> SpecialistId { get; set; }
        public string Diagnose { get; set; }
        public string Zhaloby { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string ClientIIN { get; set; }
    }
}
