CREATE TABLE [dbo].[Clients]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[IIN] NVARCHAR(12) NULL,
	[FirstName] NVARCHAR(50) NULL,
	[LastName] NVARCHAR(150) NULL,
	[Address] NVARCHAR(350) NULL,
	[Phone] NVARCHAR(100) NULL
)
